name: Commitizen Release Job

on:
  workflow_call:
    inputs:
      dry_run:            # true  → preview em PRs
        type: boolean
        default: false
    outputs:
      version:
        value: ${{ jobs.cz.outputs.version }}
      changed:
        value: ${{ jobs.cz.outputs.changed }}

jobs:
  cz:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version || steps.bump_preview.outputs.version }}
      changed: ${{ steps.bump.outputs.changed || steps.bump_preview.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install Commitizen
        run: pip install -e ".[dev]"      # commitizen vem na extra dev

      # ─────────────── Pré-visualização (PR) ───────────────
      - name: Preview next version
        if: inputs.dry_run
        id: bump_preview
        env: { CZ_PREVIEW: 1 }
        run: |
          NEXT=$(cz bump --dry-run --increment auto --changelog | tail -n1 | awk '{print $NF}')
          echo "version=$NEXT"   >> $GITHUB_OUTPUT
          echo "changed=true"    >> $GITHUB_OUTPUT
          echo "Preview version: $NEXT"

      # ─────────────── Release real (main) ────────────────
      - name: Bump + changelog + tag
        if: ${{ !inputs.dry_run }}
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          cz bump --yes --changelog --push
          echo "version=$(cz version)"   >> $GITHUB_OUTPUT
          echo "changed=true"            >> $GITHUB_OUTPUT
