name: Push para Main

on:
  push:
    branches: [main]

jobs:
  # Etapa 1: Gerar nova versão com semantic-release
  release:
    uses: ./.github/workflows/semantic-release.yaml
    with:
      dry_run: false

  # Etapa 2: Publicar no PyPI
  publish-prod:
    needs: [release]
    if: always()
    uses: ./.github/workflows/pypi-publish.yaml
    with:
      environment: 'pypi'
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
