name: Publicar no PyPI após release

on:
  push:
    tags:
      - 'v*'  # Executa quando uma tag de versão é criada

jobs:
  # Publicar no PyPI após release
  publish-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests packaging

      # Verifica se a versão já existe no PyPI
      - name: Check PyPI Version
        id: check_version
        run: |
          # Extrai a versão da tag (remove o 'v' inicial)
          VERSION=${GITHUB_REF#refs/tags/v}

          # Função para verificar se a versão existe no PyPI
          check_pypi() {
            # Extrai o nome do pacote do setup.py ou pyproject.toml
            PACKAGE_NAME=$(python -c "from setuptools import setup; setup()" --name 2>/dev/null || python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['name'])")

            # Verifica se a versão existe no PyPI
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/pypi/$PACKAGE_NAME/$VERSION/json)

            if [ "$STATUS_CODE" = "200" ]; then
              echo "true"
            else
              echo "false"
            fi
          }

          # Verifica e define o output
          EXISTS=$(check_pypi)
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT

          if [ "$EXISTS" = "true" ]; then
            echo "Versão $VERSION já existe no PyPI. Pulando publicação."
          else
            echo "Versão $VERSION não existe no PyPI. Prosseguindo com publicação."
          fi

      # Publica no PyPI apenas se a versão não existir
      - name: Publicar no PyPI
        if: steps.check_version.outputs.exists != 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
          verbose: true
          print-hash: true
