name: PR Main Flow

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

# Permissões globais do workflow
permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  # 1 - Pre-commit
  lint:
    uses: ./.github/workflows/pre-commit.yaml

  test:
    uses: ./.github/workflows/test.yaml

  # Preview da próxima versão
  version-preview:
    needs: [lint, test]
    uses: ./.github/workflows/version-preview.yaml

  # Build e release
  release:
    needs: [version-preview]
    if: ${{ needs.version-preview.outputs.next_version != '' }}
    uses: ./.github/workflows/release.yaml

  # Status final do PR
  pr-status:
    needs: [release]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Verificar Status do Release
        if: ${{ needs.release.result != 'success' }}
        run: |
          echo "Falha no processo de release e publicação"
          echo "Por favor, verifique os logs para mais detalhes"
          exit 1
