name: PR para Main

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  # Etapa 1: Verificar com pre-commit
  lint:
    uses: ./.github/workflows/pre-commit.yaml

  # Etapa 2: Executar testes
  test:
    uses: ./.github/workflows/test.yaml

  # Etapa 3: Simular semantic-release
  version-preview:
    needs: [lint, test]
    if: success()
    uses: ./.github/workflows/semantic-release.yaml
    with:
      dry_run: true

  # Etapa 4: Publicar no TestPyPI
  publish-test:
    needs: [version-preview]
    if: success()
    uses: ./.github/workflows/pypi-publish.yaml
    with:
      environment: 'testpypi'
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
