name: PR Main Flow

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

# Permissões globais do workflow
permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  # 1 - Pre-commit
  lint:
    uses: ./.github/workflows/pre-commit.yaml

  test:
    uses: ./.github/workflows/test.yaml

  # Preview da próxima versão
  version-preview:
    needs: [lint, test]
    uses: ./.github/workflows/version-preview.yaml

  # Build de teste
  build-test:
    needs: [version-preview]
    if: ${{ needs.version-preview.outputs.next_version != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: dist/
