name: PR Main Flow

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

# Permissões globais do workflow
permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  # 1 - Pre-commit
  lint:
    uses: ./.github/workflows/pre-commit.yaml

  test:
    uses: ./.github/workflows/test.yaml

  version-preview:
    needs: [lint, test]
    uses: ./.github/workflows/version-preview.yaml

  # 4 - Publicar no TestPyPI
  publish-test:
    needs: [version-preview]
    if: ${{ needs.version-preview.outputs.next_version != '' && success() }}
    uses: ./.github/workflows/pypi-publish.yaml
    with:
      repository: ${{ github.repository }}
      test_publish: true
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
