name: PR Main Flow

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

# Global workflow permissions
permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  # 1 - Pre-commit
  lint:
    uses: ./.github/workflows/pre-commit.yaml

  test:
    uses: ./.github/workflows/test.yaml

  # Preview of next version
  version-preview:
    needs: [lint, test]
    uses: ./.github/workflows/version-preview.yaml

  # Build and release
  release:
    needs: [version-preview]
    if: ${{ needs.version-preview.outputs.next_version != '' }}
    uses: ./.github/workflows/release.yaml

  # Final PR status
  pr-status:
    needs: [release]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check Release Status
        if: ${{ needs.release.result != 'success' }}
        run: |
          echo "Failure in release and publishing process"
          echo "Please check the logs for more details"
          exit 1
