name: Automatic Release

on:
  workflow_call:
    outputs:
      version:
        description: "Published version"
        value: ${{ jobs.auto-release.outputs.version }}

jobs:
  auto-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      version: ${{ steps.next-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine next version and create tag
        id: next-version
        run: |
          # Install standard-release
          npm install -g standard-version

          # Run standard-version to create tag and changelog
          standard-version

          # Extract version from the latest tag
          VERSION=$(git describe --abbrev=0 --tags | sed 's/^v//')

          if [ -z "$VERSION" ]; then
            echo "Error generating version"
            exit 1
          fi

          echo "Next version: v$VERSION"
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

          # Push changes and tag to PR branch
          git push --follow-tags origin HEAD:${{ github.head_ref }}

      - name: Create GitHub Release
        if: steps.next-version.outputs.version != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next-version.outputs.version }}
          generate_release_notes: true
          draft: true  # Create as draft since it hasn't been merged yet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-test:
    needs: auto-release
    if: needs.auto-release.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        continue-on-error: true # Don't fail if version already exists
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        run: |
          if ! twine upload dist/* 2>&1 | grep -q "File already exists"; then
            # If "File already exists" not found in error, propagate error
            twine upload dist/*
          else
            echo "Version already exists on TestPyPI - continuing..."
          fi

      - name: Test TestPyPI installation
        run: |
          # Create virtual environment for testing
          python -m venv test_env
          source test_env/bin/activate

          # Wait a bit to ensure package is available
          sleep 30

          # Try to install from TestPyPI
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ synapstor

  publish-prod:
    needs: [auto-release, publish-test]
    if: needs.auto-release.result == 'success' && needs.publish-test.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        continue-on-error: true # Don't fail if version already exists
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          if ! twine upload dist/* 2>&1 | grep -q "File already exists"; then
            # If "File already exists" not found in error, propagate error
            twine upload dist/*
          else
            echo "Version already exists on PyPI - continuing..."
          fi
