name: Test Job

on:
  workflow_call:
    outputs:
      success:
        description: "Indicates if tests passed"
        value: ${{ jobs.test.outputs.success }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.test-result.outputs.success }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install Test Dependencies
        run: pip install -e ".[test]"

      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings -q

      - id: test-result
        if: ${{ success() }}
        run: echo "success=true" >> $GITHUB_OUTPUT

      - name: Fail if tests failed
        if: ${{ failure() }}
        run: exit 1