name: Version Preview

on:
  workflow_call:
    outputs:
      next_version:
        description: "Next calculated version"
        value: ${{ jobs.version-preview.outputs.next_version }}

jobs:
  version-preview:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.preview.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Standard Release
        run: npm install -g standard-version

      - name: Preview Next Version
        id: preview
        run: |
          # Run standard-version in dry-run mode and capture output
          OUTPUT=$(standard-version --dry-run)

          # Extract version from output
          VERSION=$(echo "$OUTPUT" | grep -oP "(?<=tagging release v)[0-9]+\.[0-9]+\.[0-9]+")

          if [ -z "$VERSION" ]; then
            echo "No changes that justify a new version"
            echo "version=" >> $GITHUB_OUTPUT
          else
            echo "Next version will be: v$VERSION"
            echo "version=v$VERSION" >> $GITHUB_OUTPUT
          fi
